### PR TITLE
Modularization and customization

### PR DESCRIPTION
**Pull request by sebastianludwig**
I'm planning to use your IQAudioRecorderController in my new app. That app has already a UINavigationController in place and I wanted to push the recorder onto it instead of presenting it modally.

I implemented that change and, while on it, tweaked a bit here and there.

What do you think?

### CODE REVIEW

**Comment by hackiftekhar** [comment]
Thanks for pull request. Will take a look. :)

**Comment by hackiftekhar** [comment]
I'm not sure if anything breaks with these huge changes.

**Comment by sebastianludwig** [comment]
Well, you never know if _anything_ broke ;-). I think if your applications using `IQAudioRecorderController` still look fine, the actual question is, if it's an improvement or not. Even if a new bug has been introduced, that can be fixed and you're still better off.

**Comment by hackiftekhar** [comment]
I think I need to look deeply inside your code and your changes before merging it. According to me it's an improvement, but need to look if this fit according to user requirement.

**Comment by sebastianludwig** [comment]
All right. Give me a shout, if you think something needs further improvement.

**Comment by sebastianludwig** [comment]
As you can see I further modularized the code and extracted as much functionality as possible from the view controller into other classes. Now it's possible to easily create a custom view controller as audio recorder for all those cases where it's necessary to have another view controller superclass than `IQAudioViewController`.

Please let me know what you think about this. Do you generally agree to this approach and intend to merge this? Otherwise I'll stop spamming this PR, just keep my fork and rename the lib.

Thanks, Seb

**Comment by hackiftekhar** [comment]
Hey @sebastianludwig I'll check your repo code and will let you know If I'm good to go with your changes or not.

**Comment by sebastianludwig** [comment]
:+1:

**Comment by hackiftekhar** [comment]
Hi Sabestian, I found that you did a good refactoring. Thank You! I'm happy to merge your changes. However this PR can't e merged automatically, I'll extract useful code according to my requirement from your repo and will merge manually. Thank You again!

**Comment by sebastianludwig** [comment]
All right. Please let me know when you're done so I can se if I can switch back to your repo and ditch my fork. Thanks!

**Pull request closed without merging**
